services:

  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm run start:dev
    working_dir: /usr/src/smart-brain-api
    ports:
      - '3000:3000'
    volumes: 
      - ./:/usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://Paul:L1ngbeck@postgres:5432/smart-brain-docker

  # Postgress
  postgres:
    build: ./postgres
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_USER: Paul
      POSTGRES_PASSWORD: L1ngbeck
      POSTGRES_DB: smart-brain-docker
