services:
  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm run start:dev
    working_dir: /usr/src/smart-brain-api
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/smart-brain-api
    # env_file:
    #   - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      RANK_API: ${RANK_API}
      CLARIFAI_API_KEY: ${CLARIFAI_API_KEY}

  # Postgress
  postgres:
    build: ./postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # Redis
  redis:
    image: redis
    ports:
      - '6379:6379'
